name: Deploy to EC2

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            sudo -u hngdevops bash <<'EOF'
              set -e
              export PATH="/home/hngdevops/.nvm/versions/node/v20.20.2/bin/pnpm"   # adjust this line
              cd /home/hngdevops/projects/hng14/job_scheduler
              echo "Pulling latest changes from master..."
              git fetch origin
              git checkout master
              git pull origin master
              echo "Installing dependencies..."
              pnpm install
              # pnpm install:ui   # only if this script exists
              echo "Building processes..."
              pnpm run build:server
              # pnpm run build:ui  # only if this script exists
              echo "Restarting pm2 processes"
              pm2 restart job-scheduler-server || true   # don't fail if not running
              pm2 restart job-scheduler-worker || true
              pm2 save
            EOF
